### ISSUE TITLE
validate args

### ISSUE THREAD

**Issue by bruab** [cs294-python/grading_tools#2]
breaks on non-int args :(

**Comment by bruab** [comment]
now it breaks on non-numeric args. e.g.

    python calculate_final_grade.py brian is dumb

**Comment by joshuacw** [comment]
Soooo...I've tried a number of different things by now to take care of non-numeric args, but nothing has been successful. :/ 
I assume that to handle non-numeric args that I have to allow strings as well. Is this correct?
I've tried both specifying the args as str, and not specifying a data type at all. 
Also, I've noticed that if I don't specify a data type for the args, then all of the checks for the point ranges are activated, regardless of the data type of the input (int, float, or even str).
Hint? 
I feel I may be overthinking this. My latest attempt was to import * from the decimal module and then check if the inputs fit the decimal data type, but this had undesirable outcomes.

**Comment by bruab** [comment]
Yeah my deliberately obscure instructions have turned out to be ... obscure.

Still, since you're so ahead of the game, I'll stay vague for just a 
little bit longer. Did you check out the link I sent about handling 
exceptions?

https://wiki.python.org/moin/HandlingExceptions

It's all about defining what kind of behavior we want. If you run 
"python calculate_final_grade.py brian is dumb" then the program 
crashes. What should it do instead? I think it's enough to say something 
like "Sorry, I was expecting numbers -- please try again" and then exit.

So the line(s) of code that cause the Exception should go inside a 'try' 
block, and the friendly error message and exit() call should go inside 
the 'except' block. If that's still not enough to go on, let me know. 
TBH my suspicion is that it's not enough to go on, but I want to find 
out for sure XD

--Brian

PS -- To accept non-numeric arguments, like "thirty-three" or "seven 
point five" would be a HUGE and terrible undertaking.
